# This is a basic workflow to help you get started with Actions

name: Compile and Upload xfw-local release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-macos:
    # The type of runner that the job will run on
    runs-on: macos-13
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.1

      # installing nodeJS
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm install --force
          npm run build-macos-x64
        # npm run build-macos-universal

      # Compress output
      - name: Compress output
        run: |
          cd out
          zip xfw-local-x64.zip -r xfw-local-darwin-x64
        # zip xfw-local-arm.zip -r xfw-local-darwin-arm64

      # Test upload
      # - name: B2 Upload ARM
      #   uses: wilsonzlin/b2-upload-action@v1.0.1
      #   id: upload-arm
      #   with:
      #     bucket: xfw-local
      #     uploadKey: xfw-local-latest-macos-arm.zip
      #     file: out/xfw-local-arm.zip
      #     keyId: ${{ secrets.B2_KEY_ID }}
      #     applicationKey: ${{ secrets.B2_APPLICATION_KEY }}
      #     contentType: application/zip

      # Test upload
      - name: B2 Upload x64
        uses: wilsonzlin/b2-upload-action@v1.0.1
        id: upload-x64
        with:
          bucket: xfw-local
          uploadKey: xfw-local-latest-macos-x64.zip
          file: out/xfw-local-x64.zip
          keyId: ${{ secrets.B2_KEY_ID }}
          applicationKey: ${{ secrets.B2_APPLICATION_KEY }}
          contentType: application/zip
  
  build-windows:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.1
      
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm install --force
          npm run build-windows

      - run: dir
      - run: dir out
      - run: dir D:\a\xfw-local\xfw-local\out\xfw-local-win32-x64

      - name: Compress output
        run: |
          tar.exe -a -c -f xfw-local-windows-x64.zip D:\a\xfw-local\xfw-local\out\xfw-local-win32-x64
          tar.exe -a -c -f xfw-local-windows-arm.zip D:\a\xfw-local\xfw-local\out\xfw-local-win32-arm

      # Test upload
      - name: B2 Upload x64
        uses: wilsonzlin/b2-upload-action@v1.0.1
        id: upload-x64
        with:
          bucket: xfw-local
          uploadKey: xfw-local-latest-windows-x64.zip
          file: xfw-local-windows-x64.zip
          keyId: ${{ secrets.B2_KEY_ID }}
          applicationKey: ${{ secrets.B2_APPLICATION_KEY }}
          contentType: application/zip

      - name: B2 Upload arm
        uses: wilsonzlin/b2-upload-action@v1.0.1
        id: upload-arm
        with:
          bucket: xfw-local
          uploadKey: xfw-local-latest-windows-arm.zip
          file: xfw-local-windows-arm.zip
          keyId: ${{ secrets.B2_KEY_ID }}
          applicationKey: ${{ secrets.B2_APPLICATION_KEY }}
          contentType: application/zip