# This is a basic workflow to help you get started with Actions

name: Compile and Upload xfw-local release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-macos:
    # The type of runner that the job will run on
    runs-on: macos-13
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.1

      # installing nodeJS
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 18

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Read Version from File
        id: read-version
        run: |
          version=$(cat version.txt)
          echo "Version: $version"
          echo "::set-output name=version::$version"

      - name: Install dependencies and build
        run: |
          npm install --force
          npm run build-macos-universal

      # Move files from build to out
      - name: Move compiled files
        run: |
          mv out/make/*x64.dmg xfw-local-x64.dmg
          mv out/make/*arm64.dmg xfw-local-arm64.dmg

      # Test upload
      - name: B2 Upload ARM
        uses: wilsonzlin/b2-upload-action@v1.0.1
        id: upload-arm
        with:
          bucket: xfw-local
          uploadKey: xfw-local-latest-macos-arm64.dmg
          file: xfw-local-arm64.dmg
          keyId: ${{ secrets.B2_KEY_ID }}
          applicationKey: ${{ secrets.B2_APPLICATION_KEY }}

      # Test upload
      - name: B2 Upload x64
        uses: wilsonzlin/b2-upload-action@v1.0.1
        id: upload-x64
        with:
          bucket: xfw-local
          uploadKey: xfw-local-latest-macos-x64.dmg
          file: xfw-local-x64.dmg
          keyId: ${{ secrets.B2_KEY_ID }}
          applicationKey: ${{ secrets.B2_APPLICATION_KEY }}

      - name: B2 Upload ARM
        uses: wilsonzlin/b2-upload-action@v1.0.1
        id: upload-arm-with-version
        with:
          bucket: xfw-local
          uploadKey: xfw-local-${{ steps.read-version.outputs.version }}-macos-arm64.dmg
          file: xfw-local-arm64.dmg
          keyId: ${{ secrets.B2_KEY_ID }}
          applicationKey: ${{ secrets.B2_APPLICATION_KEY }}

      # Test upload
      - name: B2 Upload x64
        uses: wilsonzlin/b2-upload-action@v1.0.1
        id: upload-x64-with-version
        with:
          bucket: xfw-local
          uploadKey: xfw-local-${{ steps.read-version.outputs.version }}-macos-x64.dmg
          file: xfw-local-x64.dmg
          keyId: ${{ secrets.B2_KEY_ID }}
          applicationKey: ${{ secrets.B2_APPLICATION_KEY }}
  
  build-windows:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.1
      
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 18
          
      - name: Install dependencies and build
        run: |
          npm ci --force
          npm run build-windows

      - name: Read Version from File
        id: read-version
        run: |
          $version= Get-Content version.txt
          Write-Output "Version: $version"
          Write-Output "##[set-output name=version]$version"

      # Move files from build to out
      - name: Move compiled files
        run: |
          move '.\out\make\squirrel.windows\x64\xfw-local-0.0.1 Setup.exe' .\xfw-local-windows-x64.exe

      # Test upload
      - name: B2 Upload x64
        uses: wilsonzlin/b2-upload-action@v1.0.1
        id: upload-x64
        with:
          bucket: xfw-local
          uploadKey: xfw-local-latest-windows-x64.exe
          file: xfw-local-windows-x64.exe
          keyId: ${{ secrets.B2_KEY_ID }}
          applicationKey: ${{ secrets.B2_APPLICATION_KEY }}

      # Test upload
      - name: B2 Upload x64
        uses: wilsonzlin/b2-upload-action@v1.0.1
        id: upload-x64-with-version
        with:
          bucket: xfw-local
          uploadKey: xfw-local-${{ steps.read-version.outputs.version }}-windows-x64.exe
          file: xfw-local-windows-x64.exe
          keyId: ${{ secrets.B2_KEY_ID }}
          applicationKey: ${{ secrets.B2_APPLICATION_KEY }}
